//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingalRJs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> NewAccountDate { get; set; }
        public string Password2 { get; set; }
        public string Password3 { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsLoggedin { get; set; }
    }
}
