<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="SignalRClient.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="/Scripts/jquery-1.8.2.min.js"></script>
<!--Reference the SignalR library. -->  
<script src="/Scripts/jquery.signalR-1.0.0.js"></script>  
  
<!--Reference the autogenerated SignalR hub script. -->  
<script src="/signalr/hubs"></script>  
</head>
<body>
 
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="Label1" runat="server" Text="Name"></asp:Label>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label2" runat="server" Text="Age"></asp:Label>
            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
            <br />
            <asp:Button ID="btn_register" runat="server" style="margin-left: 54px" Text="Get Name Details" Width="219px" />
        </div>
    </form>

    <script type="text/javascript">  

        $(function () {

            // Declare a proxy to reference the hub.   
            var chatHub = $.connection.ChatHub;

            registerClientMethods(chatHub);

            // Start Hub  
            $.connection.hub.start().done(function () {

                registerEvents(chatHub)

            });

        });
        function registerEvents(chatHub) {

            $("#btn_register").click(function () {

                var name = $("#TextBox1").val();
                var Age = $("#TextBox2").val();

                if (name.length > 0) {
                    ChatHub.server.connect(name, Age);  //It will call the connect method on Hub
                }
                else {
                    alert("Please enter name");
                }

            });

    </script>  
</body>
</html>
